apiVersion: v1
kind: Service
metadata:
  name: chandao
  namespace: devops
  labels:
    app: chandao
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      nodePort: 30001
  selector:
    app: chandao
