apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: probe
    app.kubernetes.io/name: black-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.3.1
    prometheus: k8s
    role: alert-rules
  name: probe-rules
  namespace: monitoring
spec:
  groups:
  - name: black-exporter
    rules:
    - alert: TCPPortCanNotConnect
      annotations:
        summary: 无法连接 {{ $labels.instance }}
      expr: probe_success{module="tcp_connect"} == 0
      for: 1m
      labels:
        severity: warning
    - alert: URLCanNotConnect
      annotations:
        summary: 无法访问 {{ $labels.instance }} 
      expr: probe_success{module="http_2xx"} == 0
      for: 1m
      labels:
        severity: warning
