apiVersion: v1
kind: Service
metadata:
  name: jew-cust-admin
  namespace: prod
  labels:
    app: jew-cust-admin
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32000
  selector:
    app: jew-cust-admin
