apiVersion: v1
kind: Service
metadata:
  name: jew-cust-java
  namespace: prod
  labels:
    app: jew-cust-java
spec:
  type: NodePort
  ports:
    - port: 9041
      nodePort: 32003
  selector:
    app: jew-cust-java
