apiVersion: v1
kind: Service
metadata:
  name: jew-cust-h5
  namespace: prod
  labels:
    app: jew-cust-h5
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32002
  selector:
    app: jew-cust-h5
