apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jew-cust-business
  namespace: prod
  labels:
    app: jew-cust-business
spec:
  replicas: 1
  serviceName: "jew-cust-business"
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: jew-cust-business
  template:
    metadata:
      labels:
        app: jew-cust-business
    spec:
      containers:
      - name: app
        image: harbor.lingfannao.net:4436/test/jew-cust-business:20220416153346 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      nodeSelector:
        kubernetes.io/hostname: hwy-prod-02
      imagePullSecrets:
      - name: hwy-harbor
