apiVersion: v1
kind: Service
metadata:
  name: verge3d 
  namespace: prod
  labels:
    app: verge3d 
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32008
  selector:
    app: verge3d 
