apiVersion: v1
kind: Service
metadata:
  name: tdrendering-java
  namespace: prod
  labels:
    app: 3drendering-java
spec:
  type: NodePort
  ports:
    - port: 7001
      nodePort: 32005
  selector:
    app: 3drendering-java
