apiVersion: v1
kind: Service
metadata:
  name: jew-cust-business
  namespace: prod
  labels:
    app: jew-cust-business
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32001
  selector:
    app: jew-cust-business
