apiVersion: v1
kind: Service
metadata:
  name: jew-cust
  namespace: prod
  labels:
    app: jew-cust
spec:
  type: NodePort
  ports:
    - port: 9041
      nodePort: 30020
  selector:
    app: jew-cust
