apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jew-cust-java
  namespace: prod
  labels:
    app: jew-cust-java
spec:
  replicas: 1
  serviceName: "jew-cust-java"
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: jew-cust-java
  template:
    metadata:
      labels:
        app: jew-cust-java
    spec:
      containers:
      - name: app
        image: harbor.lingfannao.net:4436/prod/jew-cust-java:20220418205036 
        command: ['java', '-jar', '/data/app.jar', '--spring.profiles.active=prod']
        ports:
        - containerPort: 9041
        resources:
          requests:
            memory: "512Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "512m"
        volumeMounts:
        - mountPath: /data/logs/jew-customized
          name: jew-cust
      nodeSelector:
        kubernetes.io/hostname: hwy-prod-02
      volumes:
      - name: jew-cust
        hostPath:
          path: /data/logs/jew-customized
          type: Directory
      imagePullSecrets:
      - name: hwy-harbor
