apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: prod
  labels:
    app: emqx
spec:
  replicas: 1
  serviceName: "emqx"
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: app
        image: emqx/emqx:v4.0.0
        ports:
        - containerPort: 18083
        # resources:
        #   requests:
        #     memory: "50Mi"
        #     cpu: "10m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "100m"
      nodeSelector:
        kubernetes.io/hostname: hwy-prod-02
      imagePullSecrets:
      - name: hwy-harbor
