apiVersion: v1
data:
  ssh.cfg: |
    server_addr: "zhubaogongyuan.cn:4443"
    trust_host_root_certs: false
    
    tunnels:
        159:
             remote_port: 20001
             proto:
                 tcp: "192.168.40.159:222"
        56:
             remote_port: 20005
             proto:
                 tcp: "192.168.40.56:222"
kind: ConfigMap
metadata:
  name: ngrok-ssh
  namespace: devops
