apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ngrok
  namespace: devops
  labels:
    app: ngrok
spec:
  replicas: 1
  serviceName: "ngrok"
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - name: ngrok-ssh
        image: harbor.lingfannao.net:4436/yunwei/ngrok:v0.2
        command: ['/app/ngrok', '-config=/app/ssh.cfg', '-log=stdout', '-log-level=INFO', 'start-all']
        volumeMounts:
        - name: ngrok-ssh
          mountPath: "/app/ssh.cfg"
          subPath: ssh.cfg
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      - name: ngrok-rdp
        image: harbor.lingfannao.net:4436/yunwei/ngrok:v0.2
        command: ['/app/ngrok', '-config=/app/rdp.cfg', '-log=stdout', '-log-level=INFO', 'start-all']
        volumeMounts:
        - name: ngrok-rdp
          mountPath: "/app/rdp.cfg"
          subPath: rdp.cfg
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      - name: ngrok-http
        image: harbor.lingfannao.net:4436/yunwei/ngrok:v0.2
        command: ['/app/ngrok', '-config=/app/http.cfg', '-log=stdout', '-log-level=INFO', 'start-all']
        volumeMounts:
        - name: ngrok-http
          mountPath: "/app/http.cfg"
          subPath: http.cfg
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: ngrok-ssh
        configMap:
          name: ngrok-ssh
          items:
          - key: ssh.cfg
            path: ssh.cfg
      - name: ngrok-rdp
        configMap:
          name: ngrok-rdp
          items:
          - key: rdp.cfg
            path: rdp.cfg
      - name: ngrok-http
        configMap:
          name: ngrok-http
          items:
          - key: http.cfg
            path: http.cfg
      imagePullSecrets:
      - name: hwyharbor
      nodeSelector:
        kubernetes.io/hostname: yw-sys-01
