apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: prod
  labels:
    app: emqx
spec:
  type: NodePort
  ports:
  - port: 1883
    nodePort: 32081
    name: porta
  - port: 18083
    nodePort: 32082
    name: portb
  - port: 8083
    nodePort: 32083
    name: portc
  - port: 8084
    nodePort: 32084
    name: portd
  selector:
    app: emqx
