apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: live-middleware
  namespace: prod
  labels:
    app: jew-cust-java
spec:
  replicas: 1
  serviceName: "live-middleware"
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: live-middleware
  template:
    metadata:
      labels:
        app: live-middleware
    spec:
      containers:
      - name: app
        image: harbor.lingfannao.net:4436/prod/live-middleware:20220420185500 
        command: ['java', '-jar', '/data/app.jar', '--spring.profiles.active=prod']
        ports:
        - containerPort: 8880
        resources:
          requests:
            memory: "512Mi"
            cpu: "50m"
          limits:
            memory: "1024Mi"
            cpu: "512m"
        # volumeMounts:
        # - mountPath: /data/logs/jew-customized
        #   name: jew-cust
      nodeSelector:
        kubernetes.io/hostname: hwy-prod-02
      # volumes:
      # - name: jew-cust
      #   hostPath:
      #     path: /data/logs/jew-customized
      #     type: Directory
      imagePullSecrets:
      - name: hwy-harbor
