kind: Pod
apiVersion: v1
metadata:
  name: test-pod
  namespace: prod
spec:
  containers:
  - name: test-pod
    image: nginx 
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/usr/share/nginx/html"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim
