apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindoc
  namespace: devops
  labels:
    app: mindoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindoc
  template:
    metadata:
      labels:
        app: mindoc
    spec:
      containers:
      - name: mindoc
        image: centos:7
        command: ['/mindoc/mindoc_linux_amd64']
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /mindoc
          name: mindoc-volume
      nodeSelector:
        kubernetes.io/hostname: yw-sys-01
      volumes:
      - name: mindoc-volume
        hostPath:
          path: /data/mindoc
          type: Directory
