apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 3pdatasyn
  namespace: prod
  labels:
    app: 3pdatasyn
spec:
  replicas: 1
  serviceName: "3pdatasyn"
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: 3pdatasyn
  template:
    metadata:
      labels:
        app: 3pdatasyn
    spec:
      containers:
      - name: app
        image: harbor.lingfannao.net:4436/prod/3pdatasyn:20220414141411 
        command: ['java', '-jar', '/data/app.jar', '--spring.profiles.active=prod']
        ports:
        - containerPort: 19001
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /data/logs/3pdatasyn
          name: 3pdatasyn
      nodeSelector:
        kubernetes.io/hostname: hwy-prod-02
      volumes:
      - name: 3pdatasyn
        hostPath:
          path: /data/logs/3pdatasyn
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: hwy-harbor
