version: '3'

services:
  mongodb:
    image: bitnami/mongodb:6.0.1
    ports:
      - "27017:27017"
    volumes:
      - '/data/mongodb/db:/bitnami/mongodb'
  # mongodb web 管理工具
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_SERVER=mongodb"
