apiVersion: v1
kind: Pod
metadata:
  name: mysql-exporter-a
  namespace: monitoring
  labels:
    k8s-app: mysql-exporter
spec:
  containers:
  - name: mysql-exporter-a
    env:
    - name: DATA_SOURCE_NAME
      value: 'exporter:TBVo!4RqH@(192.168.40.185:3306)/'
    image: prom/mysqld-exporter:v0.14.0 
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9104
      name: port-a
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-exporter-b
  namespace: monitoring
  labels:
    k8s-app: mysql-exporter
spec:
  containers:
  - name: mysql-exporter-b
    env:
    - name: DATA_SOURCE_NAME
      value: 'exporter:TBVo!4RqH@(192.168.40.79:3306)/'
    image: prom/mysqld-exporter:v0.14.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9104
      name: port-b
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-exporter-c
  namespace: monitoring
  labels:
    k8s-app: mysql-exporter
spec:
  containers:
  - name: mysql-exporter-c
    env:
    - name: DATA_SOURCE_NAME
      value: 'exporter:TBVo!4RqH@(192.168.40.200:3306)/'
    image: prom/mysqld-exporter:v0.14.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 9104
      name: port-c
