apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mysql-exporter
  namespace: monitoring
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: port-a
    path: /metrics
    relabelings:
    - action: replace
      sourceLabels: 
      - instance
      regex: (.*)
      targetLabel: instance
      replacement: '192.168.40.185:3306'
  - interval: 30s
    port: port-b
    path: /metrics
    relabelings:
    - action: replace
      sourceLabels:
      - instance
      regex: (.*)
      targetLabel: instance
      replacement: '192.168.40.79:3306'
  - interval: 30s
    port: port-c
    path: /metrics
    relabelings:
    - action: replace
      sourceLabels:
      - instance
      regex: (.*)
      targetLabel: instance
      replacement: '192.168.40.200:3306'
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      k8s-app: mysql-exporter
