apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: mysql-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.3.1
    prometheus: k8s
    role: alert-rules
  name: mysql-exporter-rules
  namespace: monitoring
spec:
  groups:
  - name: mysql-exporter
    rules:
    - alert: MySQLNotRunning
      annotations:
        description: MySQL 实例 {{ $labels.instance }} 停止运行
      expr: mysql_up == 0
      for: 1m
      labels:
        severity: warning