apiVersion: apps/v1
kind: Deployment
metadata:
  name: eolinker
  namespace: devops
  labels:
    app: eolinker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eolinker
  template:
    metadata:
      labels:
        app: eolinker
    spec:
      containers:
      - name: chandao
        image: harbor.lingfannao.net:4436/yunwei/eolinker:v6.0
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      imagePullSecrets:
      - name: hwyharbor
