apiVersion: v1
kind: Service
metadata:
  name: eolinker
  namespace: devops
  labels:
    app: eolinker
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30002
  selector:
    app: eolinker
