apiVersion: apps/v1
kind: Deployment
metadata:
  name: dingding
  namespace: monitoring
  labels:
    app: dingding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dingding
  template:
    metadata:
      labels:
        app: dingding
    spec:
      containers:
      - name: dingding
        image: timonwong/prometheus-webhook-dingtalk:v2.0.0
        # command: ['sleep','1d']
        # image: harbor.lingfannao.net:4436/common/dingtalk:20220414183352
        # command: ["./app", "-defaultRobot=https://oapi.dingtalk.com/robot/send?access_token=94747def79a6288d3c054b6abb83afb29a42b0678e685bc8f9888b74d0f5d95f"]
        ports:
        - containerPort: 8060
        volumeMounts:
        - name: config
          mountPath: "/etc/prometheus-webhook-dingtalk/config.yml"
          subPath: config.yml
          readOnly: true
        - name: config
          mountPath: "/etc/prometheus-webhook-dingtalk/templates/default.tmpl"
          subPath: default.tmpl
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: dingding-config
          items:
          - key: "config.yml"
            path: "config.yml"
          - key: "default.tmpl"
            path: "default.tmpl"
      imagePullSecrets:
      - name: hwy-harbor
