apiVersion: v1
kind: Service
metadata:
  name: doplat
  namespace: devops
  labels:
    app: doplat
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      nodePort: 30004
  selector:
    app: doplat
