apiVersion: v1
kind: Service
metadata:
  name: tdrendering-web
  namespace: prod
  labels:
    app: 3drendering-web
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32004
  selector:
    app: 3drendering-web
