apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 3drendering-java
  namespace: prod
  labels:
    app: 3drendering-java
spec:
  replicas: 1
  serviceName: "3drendering-java"
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: 3drendering-java
  template:
    metadata:
      labels:
        app: 3drendering-java
    spec:
      containers:
      - name: app
        image: harbor.lingfannao.net:4436/prod/3drendering:20220414144939 
        command: ['java', '-jar', '/data/app.jar', '--spring.profiles.active=prod']
        ports:
        - containerPort: 7001
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /data/logs/3drendering
          name: 3drendering
      - name: redis
        image: redis:6.2.6 
        command:  [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 250m
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-conf
          mountPath: "/usr/local/etc/redis"
          readOnly: true
      nodeSelector:
        kubernetes.io/hostname: hwy-prod-02
      volumes:
      - name: 3drendering
        hostPath:
          path: /data/logs/3drendering
          type: DirectoryOrCreate
      - name: redis-conf
        configMap:
          name: 3drendering-redis
      imagePullSecrets:
      - name: hwy-harbor
      hostAliases:
      - ip: "192.168.1.201"
        hostnames:
        - "lfn-mysql80"
