apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*prod*.log
        - /var/log/containers/*test*.log
        - /var/log/containers/*monitoring*.log
        - /var/log/containers/*kube-system*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
    filebeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: true
    setup.template.settings:
      index.number_of_shards: 1
    setup.kibana:
      host: "172.18.148.238:5601"
    setup.ilm.enabled: false
    setup.template.name: "pro_log"
    setup.template.pattern: "filebeat"
    setup.template.overwrite: true
    setup.template.enabled: true
    output.elasticsearch:
      hosts: ["192.168.1.155:9200"]
      index: "%{[kubernetes.namespace]}_%{[kubernetes.pod.name]}_%{+yyyy.MM.dd}"
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
