apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yibeizi 
  namespace: prod
  labels:
    app: yibeizi
spec:
  replicas: 1
  serviceName: "yibeizi"
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: yibeizi
  template:
    metadata:
      labels:
        app: yibeizi
    spec:
      containers:
      - name: app
        image: harbor.lingfannao.net:4436/prod/yibeizi:20220419160023 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      nodeSelector:
        kubernetes.io/hostname: hwy-prod-02
      imagePullSecrets:
      - name: hwy-harbor
